FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy source code files
COPY src/ ./src/

CMD ["sh", "-c", "streamlit run src/frontend.py --server.headless true --server.port ${PORT:-8501} --server.address 0.0.0.0"]
